### ISSUE TITLE
generating transparent png for some densities. 

### ISSUE THREAD

**Issue by vedhavyas** [trello/victor#42]
generating expected png for mdpi and hdpi but gives out empty png for xhdpi and xxhdpi

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="50px" height="46px" viewBox="0 0 50 46" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    
    <title>arrows-48px-outline-2_circle-out</title>
    <desc>Created with Sketch.</desc>
    <defs>
        <filter x="-50%" y="-50%" width="200%" height="200%" filterUnits="objectBoundingBox" id="filter-1">
            <feOffset dx="0" dy="0" in="SourceAlpha" result="shadowOffsetOuter1"/>
            <feGaussianBlur stdDeviation="6" in="shadowOffsetOuter1" result="shadowBlurOuter1"/>
            <feColorMatrix values="0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.21 0" in="shadowBlurOuter1" type="matrix" result="shadowMatrixOuter1"/>
            <feMerge>
                <feMergeNode in="shadowMatrixOuter1"/>
                <feMergeNode in="SourceGraphic"/>
            </feMerge>
        </filter>
    </defs>
    <g id="Mar-16-W1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" filter="url(#filter-1)">
        <g id="Home-Copy-28" transform="translate(-137.000000, -428.000000)" stroke-width="2" stroke="#FFFFFF">
            <g id="Oval-184-+-₹--+-Rectangle-582-Copy-+-Split-Expense-+-Request" transform="translate(133.000000, 424.000000)">
                <g id="arrows-48px-outline-2_circle-out" transform="translate(29.000000, 27.000000) rotate(-180.000000) translate(-29.000000, -27.000000) translate(16.000000, 17.000000)">
                    <g id="Group">
                        <path d="M6.625,15 C8.375,18 11.5625,20 15.25,20 C20.75,20 25.25,15.5 25.25,10 C25.25,4.5 20.75,0 15.25,0 C11.5625,0 8.3125,2 6.625,5" id="Shape"/>
                        <path d="M17.5,10 L7.10542736e-15,10" id="Shape"/>
                        <path d="M3.75,13.75 L0,10 L3.75,6.25" id="Shape"/>
                    </g>
                </g>
            </g>
        </g>
    </g>
</svg>`

this is one svg that wasnt working.

**Comment by dlew** [comment]
I tried converting it using the command-line batik, and it fails whenever trying to scale up the image with this exception:

```java
java.awt.image.ImagingOpException: Unable to transform src image
	at java.awt.image.AffineTransformOp.filter(AffineTransformOp.java:285)
	at org.apache.batik.ext.awt.image.rendered.AffineRed.genRect(Unknown Source)
	at org.apache.batik.ext.awt.image.rendered.AffineRed.copyData(Unknown Source)
	at org.apache.batik.ext.awt.image.rendered.PadRed.copyData(Unknown Source)
	at org.apache.batik.ext.awt.image.rendered.ColorMatrixRed.copyData(Unknown Source)
	at org.apache.batik.ext.awt.image.rendered.PadRed.copyData(Unknown Source)
	at org.apache.batik.ext.awt.image.rendered.CompositeRed.genRect(Unknown Source)
	at org.apache.batik.ext.awt.image.rendered.CompositeRed.copyData(Unknown Source)
	at org.apache.batik.ext.awt.image.rendered.Any2sRGBRed.copyData(Unknown Source)
	at org.apache.batik.ext.awt.image.rendered.FormatRed.copyData(Unknown Source)
	at org.apache.batik.ext.awt.image.rendered.AbstractRed.getData(Unknown Source)
	at org.apache.batik.ext.awt.image.GraphicsUtil.drawImage(Unknown Source)
	at org.apache.batik.ext.awt.image.GraphicsUtil.drawImage(Unknown Source)
	at org.apache.batik.ext.awt.image.renderable.PadRable8Bit.paintRable(Unknown Source)
	at org.apache.batik.ext.awt.image.GraphicsUtil.drawImage(Unknown Source)
	at org.apache.batik.ext.awt.image.renderable.PadRable8Bit.paintRable(Unknown Source)
	at org.apache.batik.ext.awt.image.GraphicsUtil.drawImage(Unknown Source)
	at org.apache.batik.ext.awt.image.renderable.FilterChainRable8Bit.paintRable(Unknown Source)
	at org.apache.batik.ext.awt.image.GraphicsUtil.drawImage(Unknown Source)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(Unknown Source)
	at org.apache.batik.gvt.CompositeGraphicsNode.primitivePaint(Unknown Source)
	at org.apache.batik.gvt.CanvasGraphicsNode.primitivePaint(Unknown Source)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(Unknown Source)
	at org.apache.batik.gvt.CompositeGraphicsNode.primitivePaint(Unknown Source)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(Unknown Source)
	at org.apache.batik.gvt.renderer.MacRenderer.repaint(Unknown Source)
	at org.apache.batik.gvt.renderer.MacRenderer.repaint(Unknown Source)
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(Unknown Source)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(Unknown Source)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(Unknown Source)
	at org.apache.batik.apps.rasterizer.SVGConverter.transcode(Unknown Source)
	at org.apache.batik.apps.rasterizer.SVGConverter.execute(Unknown Source)
	at org.apache.batik.apps.rasterizer.Main.execute(Unknown Source)
	at org.apache.batik.apps.rasterizer.Main.main(Unknown Source)
```

It seems to be an issue with either the JDK or batik. Unfortunately I don't think there are any workarounds except making your SVG something that batik can rasterize.

I have tracked it down to `filter="url(#filter-1)"` causing the problem - but without it, obviously, things look quite a bit different.
